# サーバー系共通処理前段
- hosts:
    - all
  become: true
  become_user: root
#  roles:
    # roleを作成してここに追加していく
#    -
  tasks:
    # roleで共通化出来ないようなタスクはここに書く
    - name: "shell test"
      command: uname -a
      register: shell_test

    - name: "dump variables shell_test"
      debug: var=shell_test
