all:
  vars:
    ansible_ssh_user: ansible
    ansible_ssh_port: 22
    ansible_ssh_private_key_file: ~/.ssh/ansible_sshkey
  children:
    # 主に開発環境(VM上などに構築環境が用意されているものを定義)
    dev:
      vars:
        ansible_connection: local
      children:
        training_dev:
          hosts:
            vm.training.cs.test:
    training:
      children:
        training_dev: {}
